language: node_js
notifications:
  email: false
node_js:
  - "10"
  - "12"
  - "13"
  - "14"
before_script:
  - "npm run build"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run test -- --coverage
        - cat coverage/lcov.info | npx coveralls
        - npx semantic-release
